on: [push]

name: test

jobs:
  check:
    name: Demonstrate how forge update breaks the package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Tests pass before update
        run: forge test -vvv

      - name: Update depencency
        run: forge update lib/outdated-foundry-package

      - name: Tests / Compilation fail after update
        run: forge test -vvv



